"""add social media and notification fields to user

Revision ID: e7a6adf2a97d
Revises: d3e4b3611382
Create Date: 2025-06-16 11:55:11.625950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7a6adf2a97d'
down_revision = 'd3e4b3611382'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('twitter', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('facebook', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('linkedin', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('email_notifications', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('push_notifications', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('push_notifications')
        batch_op.drop_column('email_notifications')
        batch_op.drop_column('linkedin')
        batch_op.drop_column('facebook')
        batch_op.drop_column('twitter')

    # ### end Alembic commands ###
